/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import TransfoGLTF from '/src/assets/model/TransfoModel.gltf?url'

type GLTFResult = GLTF & {
  nodes: {
    ['101744']: THREE.Mesh
    ['グループ#11']: THREE.Mesh
    ['259144']: THREE.Mesh
    ['271551']: THREE.Mesh
    ['271544']: THREE.Mesh
    ['271532']: THREE.Mesh
    ['271547']: THREE.Mesh
    Groundfloor: THREE.Mesh
    ['271527']: THREE.Mesh
    ['271615']: THREE.Mesh
    ['271543']: THREE.Mesh
    ['271549']: THREE.Mesh
    ['271475']: THREE.Mesh
    ['271529']: THREE.Mesh
    ['271546']: THREE.Mesh
    ['271548']: THREE.Mesh
    ['271526']: THREE.Mesh
    ['271533']: THREE.Mesh
    ['271614']: THREE.Mesh
    Edge015: THREE.Mesh
    ['271607']: THREE.Mesh
    ['271535']: THREE.Mesh
    ['271525']: THREE.Mesh
    ['271552']: THREE.Mesh
    ['271545']: THREE.Mesh
    ['270643']: THREE.Mesh
    ['271528']: THREE.Mesh
    ['271531']: THREE.Mesh
    ['271530']: THREE.Mesh
    ['271542']: THREE.Mesh
    ['101747']: THREE.Mesh
    ['101748']: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(TransfoGLTF) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['101744'].geometry}
        material={materials['Material.002']}
        position={[265.7, 4.42, 119.24]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['グループ#11'].geometry}
        material={materials['Material.032']}
        position={[198.95, 40.85, 131.9]}
        rotation={[-Math.PI / 2, 0, 1.04]}
        scale={0.01}
      />
      <mesh
        geometry={nodes['259144'].geometry}
        material={materials['Material.006']}
        position={[76.57, 10.37, -68.9]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271551'].geometry}
        material={materials['Material.035']}
        position={[52.95, 5.84, -66.28]}
        rotation={[-Math.PI / 2, 0, 0.06]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271544'].geometry}
        material={materials['Material.021']}
        position={[90.66, 5.84, 64.48]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271532'].geometry}
        material={materials['Material.016']}
        position={[19.18, 5.84, -126.62]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271547'].geometry}
        material={materials['Material.023']}
        position={[-159.31, 5.84, 11.71]}
        rotation={[-Math.PI / 2, 0, 0.86]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Groundfloor.geometry}
        material={materials['Material.018']}
        position={[123.99, 5.84, -22.04]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271527'].geometry}
        material={materials['Material.011']}
        position={[110.07, 5.84, -9.74]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271615'].geometry}
        material={materials['Material.030']}
        position={[17.24, 5.84, -165.83]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271543'].geometry}
        material={materials['Material.020']}
        position={[67.69, 5.84, -7.36]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271549'].geometry}
        material={materials['Material.025']}
        position={[123.99, 6.84, -22.03]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271475'].geometry}
        material={materials['Material.008']}
        position={[126.31, 5.84, -53.04]}
        rotation={[-Math.PI / 2, 0, 0.06]}
        scale={[0.02, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes['271529'].geometry}
        material={materials['Material.013']}
        position={[33.82, 1.84, -15.24]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271546'].geometry}
        material={materials['Material.022']}
        position={[-170.72, 5.84, 31.8]}
        rotation={[-Math.PI / 2, 0, 1.43]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271548'].geometry}
        material={materials['Material.024']}
        position={[59.08, 5.84, -130.31]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={[0.03, 0.03, 0.08]}
      />
      <mesh
        geometry={nodes['271526'].geometry}
        material={materials['Material.010']}
        position={[82.5, 5.84, -33.07]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271533'].geometry}
        material={materials['Material.017']}
        position={[70.62, 5.84, -18.97]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271614'].geometry}
        material={materials['Material.029']}
        position={[-135.72, 5.84, -22.69]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Edge015.geometry}
        material={materials['Material.031']}
        position={[140.84, 5.84, 86.76]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271607'].geometry}
        material={materials['Material.036']}
        position={[26.92, 5.84, 61.8]}
        rotation={[-Math.PI / 2, 0, 2.04]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271535'].geometry}
        material={materials['Material.001']}
        position={[1.32, 5.84, -39.22]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271525'].geometry}
        material={materials['Material.009']}
        position={[93.33, 5.84, -39.09]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271552'].geometry}
        material={materials['Material.026']}
        position={[26.56, 5.84, -84.45]}
        rotation={[-Math.PI / 2, 0, 0.7]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271545'].geometry}
        material={materials['Material.034']}
        position={[180.82, 5.84, -5.67]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['270643'].geometry}
        material={materials['Material.007']}
        position={[83.09, 8.99, -124.57]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={[0.03, 0.03, 0.02]}
      />
      <mesh
        geometry={nodes['271528'].geometry}
        material={materials['Material.012']}
        position={[13.19, 5.84, -30.46]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271531'].geometry}
        material={materials['Material.015']}
        position={[48.4, 5.84, -140.56]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271530'].geometry}
        material={materials['Material.014']}
        position={[15.33, 5.84, -148.46]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['271542'].geometry}
        material={materials['Material.019']}
        position={[60.18, 5.84, -43.44]}
        rotation={[-Math.PI / 2, 0, 2.08]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['101747'].geometry}
        material={materials['Material.004']}
        position={[24.26, 6.06, 22.09]}
        rotation={[-Math.PI / 2, 0, 0.6]}
        scale={0.03}
      />
      <mesh
        geometry={nodes['101748'].geometry}
        material={materials['Material.005']}
        position={[192.28, 6.06, 12.52]}
        rotation={[-Math.PI / 2, 0, 1.69]}
        scale={0.03}
      />
    </group>
  )
}

useGLTF.preload(TransfoGLTF)
